---
- name: Install required system packages
  apt:
    pkg: "{{ docker_dependencies }}"
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: "{{ docker_apt_key_url }}"
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present

- name: Update apt and install Docker package
  apt:
    name: "{{ docker_package }}={{ docker_version }}"
    state: present
    update_cache: true

- name: Add current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
